catalog/urls.py
from django.urls import path
from . import views

#app_name = 'catalog'
urlpatterns = [
  path('', views.index, name='index'),
  path('students/', views.StudentListView.as_view(), name='students'),
  path('introduction_page/', views.introduction_page, name='introduction_page'),
  path('counting_principle/', views.counting_principle , name='counting_principle'),
  path('login/', views.login , name='login'),
  path('logout/', views.logout , name='logout'),
  path('personal_page/', views.personal_page , name='personal_page'),
  path('uploadFile/', views.uploadFile , name='uploadFile'),
  #path('ScoreBoard/', views.ScoreBoard, name='ScoreBoard'),
]

jumping_site/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]


# Use include() to add paths from the catalog application
from django.conf.urls import include
from django.urls import path

urlpatterns += [
    path('catalog/', include('catalog.urls')),
]


#Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='/catalog/login')),
]

# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

'''
urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
'''

catalog/models.py
from djongo import models

'''
class school(models.Model):
  name=models.CharField(max_length=20)
    
  class Meta:
    verbose_name = '學校資訊'
    verbose_name_plural = verbose_name
  def __str__(self):
    return self.name
'''
    
    
class student(models.Model):
  _id   = models.ObjectIdField()
  school= models.CharField(max_length=20, verbose_name='學校')
  item  = models.CharField(max_length=20, verbose_name='項目')
  group = models.CharField(max_length=20, verbose_name='組別')
  grade = models.CharField(max_length=20, verbose_name='年級')
  coach = models.CharField(max_length=20, verbose_name='指導老師')
  std_No=models.CharField(max_length=20, verbose_name='號碼')
  name  =models.CharField(max_length=20, verbose_name='姓名')
  score =models.IntegerField(verbose_name='次數',null=True)
  class Meta:
    ordering = ('-score',)
    verbose_name = '學生資訊'
    verbose_name_plural = verbose_name
  #def __str__(self):
  #  return self.std_No
# Create your models here.

catalog/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
# Create your views here.
from .models import student


def index(request):
    """View function for home page of site."""

    # Generate counts of some of the main objects
    num_students = student.objects.all().count()

    # Available books (status = 'a')
    #num_instances_available = BookInstance.objects.filter(status__exact='a').count()

    # The 'all()' is implied by default.
    #num_authors = Author.objects.count()

    context = {
        'num_students': num_students,
    }
    model=student
    # Render the HTML template index.html with the data in the context variable
    return render(request, 'index.html', context=context)
    
    
from django.views import generic
from django.http import HttpResponse
import os

class StudentListView(generic.ListView):
    model = student
    
def introduction_page(request):
    return render(request,"catalog/introduction_page.html",locals())
    
def counting_principle(request):
    return render(request, 'catalog/counting_principle.html', locals())
    
def login(request):
    if request.method=="POST":
        username = request.POST.get("username")
        #passwd = request.POST.get("password")
        #print("student.objects.get(std_No==username):", student.objects.filter(std_No=username, passwd=passwd))
        print("student.objects.get(std_No==username):", student.objects.filter(std_No=username))
        try:
            username = username.upper()
            student.objects.get(std_No=username)
            students = student.objects.get(std_No=username)
            request.session['is_login'] = True
            request.session['username'] = username
            request.session['name'] = students.name
            return render(request, "catalog/personal_page.html", locals())
        except:
            error_msg = "無此代號"
            return render(request, 'catalog/login.html', {'login_error_msg':error_msg})
    else:
        if(request.session.get('is_login')):
            return render(request, 'catalog/personal_page.html', locals())
    return render(request, 'catalog/login.html', locals())
    
    
def logout(request):
    request.session.delete()
    return redirect('/catalog/login/')
    
def personal_page(request):
    if(request.session.get('is_login')):
        username = request.session.get('username')
        students = student.objects.get(std_No=username)
        return render(request, 'catalog/personal_page.html', locals())
    return HttpResponse("尚未登入!")
    #return HttpResponseRedirect('catalog/personal_page.html')


from catalog.tasks import task_count
from django.urls import reverse
    
def uploadFile(request):
    if request.method == "POST":
        myFile =request.FILES.get("myfile", None)
        if not myFile:  
            return HttpResponse("no files for upload!")  
        username = request.session.get('username')
        path='Video/'+username
        if not (os.path.exists(path)):
            os.mkdir(path)
        destination = open(os.path.join(path, myFile.name),'wb+')
        for chunk in myFile.chunks(): 
            destination.write(chunk)  
        destination.close()
        score = task_count.apply_async((username, myFile.name))
        
        return render(request, 'catalog/success_upload.html')

catalog/templates/catalog/ScoreBoard.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>ScoreBoard</h1>
  {% if student_list %}
  <ul>
    {% for student in student_list %}
      <li>
        <a>{{ student.school }} {{student.std_No}} {{student.name}} {{student.score}}</a>
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no books in the library.</p>
  {% endif %} 
{% endblock %}

catalog/templates/catalog/counting_principle.html
{% extends "base_generic.html" %}

{% block title %}<title>計數原理</title>{% endblock %}
{% block content %}
  <h1>計數原理</h1>
  <p>跳繩跳繩跳繩的計數原理 by <em>charlie lin</em></p>

   <!-- The video tag: -->
  {% load static %}
  <video name='demo' controls autoplay width='50%' height='40%'>
    <source src="{% static 'img/part1.mp4' %}"></source>
  </video>
  <!-- Or embed shortcut: -->
  <marquee scrollamount="10">跳繩影片</marquee>
{% endblock %}

catalog/templates/catalog/introduction_page.html
{% extends "base_generic.html" %}

{% block title %}<title>簡介</title>{% endblock %}
{% block content %}
  <h1>簡介</h1>
  <p>跳繩跳繩跳繩的研究動機 by <em>charlie lin</em></p>

{% endblock %}

catalog/templates/catalog/personal_page.html
{% extends "base_generic.html" %}

{% block title %}<title>計數原理</title>{% endblock %}
{% block content %}

<style>
body{
	font-family:"DFKai-sb";
	font-size:15pt;
	text-align: center;
	align-items:center;
	justify-content:center;
	background-color:#F0F0F0;
}
hr.style-seven {
    overflow: visible; /* For IE */
    height: 30px;
    border-style: solid;
    border-color: black;
    border-width: 1px 0 0 0;
    border-radius: 20px;
}
hr.style-seven:before { /* Not really supposed to work, but does */
    display: block;
    content: "";
    height: 30px;
    margin-top: -31px;
    border-style: solid;
    border-color: black;
    border-width: 0 0 1px 0;
    border-radius: 20px;
}
</style>

<body>
	<h1 style="font-size:35pt">{{ request.session.name }}的個人頁面</h1>
	<div style="width:80%; margin:0 auto;"><hr class="style-seven"></hr></div>
	<h1 style="font-size:40px"><em>請上傳跳繩影片</em></p>
	<div>
	<form enctype="multipart/form-data" action="{% url 'uploadFile' %}" method="post">{% csrf_token %}
		<input type="file" name="myfile" style="text-align-last: center; width:100%;" />  
		<br/>
		<input type="submit" value="上傳"/>  
	</form>
	</div>	
</body>
{% endblock %}

catalog/templates/catalog/student_list.html
{% extends "base_generic.html" %}

{% block content %}
  
<head> 
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/rank_style.css' %}">
</head> 

<style>
body{
	background-color: #F0F0F0	;
	font-family:"DFKai-sb";
}
hr.style-seven {
    overflow: visible; /* For IE */
    height: 30px;
    border-style: solid;
    border-color: black;
    border-width: 1px 0 0 0;
    border-radius: 20px;
}
hr.style-seven:before { /* Not really supposed to work, but does */
    display: block;
    content: "";
    height: 30px;
    margin-top: -31px;
    border-style: solid;
    border-color: black;
    border-width: 0 0 1px 0;
    border-radius: 20px;
}
</style>
<body>
 <h1 align="center" style="font-size:35pt">跳繩排行榜</h1>
	<div style="width:80%; margin:0 auto;"><hr class="style-seven"></hr></div>
  {% if student_list %}
  <div class="table">
   <table>
    <thead>
        <tr>
			<th width="50">名次</th>
            <th>學校</th>
			<th>代號</th>
			<th>姓名</th>
			<th>跳繩次數</th>
        </tr>
    </thead>
    <tbody>
		{% for student in student_list %}
        <tr>
			<td>{{ forloop.counter }}</td>
            <td>{{ student.school }}</td>
            <td>{{ student.std_No }}</td>
			<td>{{ student.name   }}</td>
			<td>{{ student.score }}</td>
        </tr>
		{% endfor %}
    </tbody>
   </table>
  </div>
  {% else %}
    <p>There are no books in the library.</p>
  {% endif %}
  
{% endblock %}
</body>

catalog/templates/catalog/success_upload.html
<body>
<h1 align="center" style="font-size:50px">上傳成功！</h1>
<div align="center">
<input type="button" onclick="javascript:location.href='../personal_page'" value="回到個人首頁" style="width:15%; height:5%; font-size:18px;"></input>
</div>
 <script>
 var x=4;
 window.onload=function () {
   setInterval(go,1000)
 };
 
 function go() {
   if (x>=0){
     document.getElementById("sp").innerText=x;
   }else {
	 location.href="/catalog/personal_page.html" rel="external nofollow" rel="external nofollow" ;
   }
   x--;
 }
</script>
</body>